spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./store/blogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;USER=root;PASSWORD=123456
    username: root
    password: 123456
  h2:
    console:
      path: /h2
      enabled: true